language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    - setup=basic


sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)